version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/pull_image
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/run_image
      timeout: 3000
      runas: root

